# Generated by Django 2.1.4 on 2019-05-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='inflation',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='business_name',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
        migrations.DeleteModel(
            name='Dates',
        ),
        migrations.DeleteModel(
            name='Inflation',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
