# Generated by Django 2.0 on 2020-05-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dates', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RampUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name to distinguish ramp ups.', max_length=50, null=True)),
                ('rampup_type', models.PositiveSmallIntegerField(blank=True, choices=[(-1, '---Select Type---'), (0, 'All Products'), (2, 'Product 1'), (3, 'Product 2'), (4, 'Tomato'), (5, 'Tomato'), (2, 'Product 1'), (3, 'Product 2'), (4, 'Tomato'), (5, 'Tomato'), (2, 'Product 1'), (3, 'Product 2'), (4, 'Tomato'), (5, 'Tomato')], help_text='Ramp Up type to be used.', null=True)),
                ('will_roll_over', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Ramp Up',
                'verbose_name_plural': 'Product Ramp Ups',
            },
        ),
        migrations.CreateModel(
            name='RampUpValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(-1, '---Select Month---'), (0, 'All'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rampup_f_year', to='dates.FinancialYear')),
                ('product', models.ManyToManyField(blank=True, related_name='product_rampup', to='products.Product')),
            ],
            options={
                'verbose_name': 'Product RampUp Value',
                'verbose_name_plural': 'Product RampUp Values',
            },
        ),
        migrations.AddField(
            model_name='rampup',
            name='rampup_values',
            field=models.ManyToManyField(blank=True, related_name='rampup_values', to='rampup.RampUpValue'),
        ),
        migrations.AddField(
            model_name='rampup',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rampup_type', to='dates.FinancialYear'),
        ),
    ]
