# Generated by Django 2.1.4 on 2019-05-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityRampUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_ramp_up_description', models.CharField(max_length=50)),
                ('month_1_ramp_up', models.FloatField(default=1.0)),
                ('month_2_ramp_up', models.FloatField(default=1.0)),
                ('month_3_ramp_up', models.FloatField(default=1.0)),
                ('month_4_ramp_up', models.FloatField(default=1.0)),
                ('month_5_ramp_up', models.FloatField(default=1.0)),
                ('month_6_ramp_up', models.FloatField(default=1.0)),
                ('month_7_ramp_up', models.FloatField(default=1.0)),
                ('month_8_ramp_up', models.FloatField(default=1.0)),
                ('month_9_ramp_up', models.FloatField(default=1.0)),
                ('month_10_ramp_up', models.FloatField(default=1.0)),
                ('month_11_ramp_up', models.FloatField(default=1.0)),
                ('month_12_ramp_up', models.FloatField(default=1.0)),
            ],
        ),
    ]
