# Generated by Django 2.0 on 2019-09-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('rampup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRampUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_rampup', to='products.Product')),
            ],
            options={
                'verbose_name': 'Product RampUp',
                'verbose_name_plural': 'Product RampUp',
            },
        ),
        migrations.DeleteModel(
            name='CapacityRampUp',
        ),
    ]
