# Generated by Django 2.0 on 2019-09-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampup', '0002_auto_20190907_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrampup',
            name='description',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
