# Generated by Django 2.0 on 2019-10-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampup', '0003_productrampup_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrampup',
            name='description',
        ),
        migrations.AddField(
            model_name='productrampup',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
    ]
