# Generated by Django 2.0 on 2019-11-12 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0005_auto_20191109_1333'),
        ('rampup', '0007_auto_20191108_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='RampUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name to distinguish ramp ups.', max_length=50, null=True)),
                ('rampup_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'For Many Products'), (1, 'For One Product')], help_text='Ramp Up type to be used.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rampup_type', to='dates.FinancialYear')),
            ],
            options={
                'verbose_name': 'Ramp Up',
                'verbose_name_plural': 'Ramp Ups',
            },
        ),
        migrations.CreateModel(
            name='RampUpValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rampup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rampup_value', to='rampup.RampUp')),
            ],
            options={
                'verbose_name': 'RampUp Value',
                'verbose_name_plural': 'RampUp Values',
            },
        ),
    ]
