# Generated by Django 2.0 on 2019-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampup', '0008_rampup_rampupvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrampup',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='productrampup',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='rampup',
            options={'verbose_name': 'Product Ramp Up', 'verbose_name_plural': 'Product Ramp Ups'},
        ),
        migrations.AlterModelOptions(
            name='rampupvalue',
            options={'verbose_name': 'Product RampUp Value', 'verbose_name_plural': 'Product RampUp Values'},
        ),
        migrations.AddField(
            model_name='rampup',
            name='will_roll_over',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductRampUp',
        ),
    ]
