# Generated by Django 2.2.7 on 2019-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampup', '0009_auto_20191112_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rampupvalue',
            name='rampup',
        ),
        migrations.AddField(
            model_name='rampup',
            name='rampup_values',
            field=models.ManyToManyField(blank=True, related_name='rampup_values', to='rampup.RampUpValue'),
        ),
    ]
