# Generated by Django 2.1.4 on 2019-05-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inflation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflation_description', models.CharField(max_length=50)),
                ('year_2_inflation', models.FloatField(default=1.06)),
                ('year_3_inflation', models.FloatField(default=1.06)),
                ('year_4_inflation', models.FloatField(default=1.06)),
                ('year_5_inflation', models.FloatField(default=1.06)),
                ('year_6_inflation', models.FloatField(default=1.06)),
                ('year_7_inflation', models.FloatField(default=1.06)),
                ('year_8_inflation', models.FloatField(default=1.06)),
                ('year_9_inflation', models.FloatField(default=1.06)),
                ('year_10_inflation', models.FloatField(default=1.06)),
            ],
        ),
    ]
