# Generated by Django 2.0 on 2019-08-20 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflation',
            options={'verbose_name': 'Inflation', 'verbose_name_plural': 'Inflations'},
        ),
        migrations.RenameField(
            model_name='inflation',
            old_name='inflation_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='inflation',
            old_name='year_10_inflation',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='inflation',
            name='year_2_inflation',
        ),
        migrations.RemoveField(
            model_name='inflation',
            name='year_3_inflation',
        ),
        migrations.RemoveField(
            model_name='inflation',
            name='year_4_inflation',
        ),
        migrations.RemoveField(
            model_name='inflation',
            name='year_5_inflation',
        ),
        migrations.RemoveField(
            model_name='inflation',
            name='year_6_inflation',
        ),
        migrations.RemoveField(
            model_name='inflation',
            name='year_7_inflation',
        ),
        migrations.RemoveField(
            model_name='inflation',
            name='year_8_inflation',
        ),
        migrations.RemoveField(
            model_name='inflation',
            name='year_9_inflation',
        ),
        migrations.AddField(
            model_name='inflation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inflation',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inflation',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
