# Generated by Django 2.0 on 2019-09-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0003_auto_20190905_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflation',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inflation',
            name='value',
            field=models.FloatField(),
        ),
    ]
