# Generated by Django 2.0 on 2019-09-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0004_auto_20190907_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflation',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='inflation',
            name='value',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='inflation',
            name='year',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
