# Generated by Django 2.0 on 2019-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0005_auto_20190907_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflation',
            name='description',
            field=models.CharField(help_text='Inflation description text', max_length=50),
        ),
        migrations.AlterField(
            model_name='inflation',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Inflation value iun percentages', max_digits=2),
        ),
        migrations.AlterField(
            model_name='inflation',
            name='value',
            field=models.PositiveSmallIntegerField(help_text='Inflation value'),
        ),
        migrations.AlterField(
            model_name='inflation',
            name='year',
            field=models.PositiveSmallIntegerField(default=2, help_text='Inflation year value'),
        ),
    ]
