# Generated by Django 2.0 on 2020-05-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dates', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name to distinguish seasonalities.', max_length=50, null=True)),
                ('seasonality_type', models.PositiveSmallIntegerField(blank=True, choices=[(-1, '---Select Type---'), (0, 'All Products'), (2, 'Product 1'), (3, 'Product 2'), (4, 'Tomato'), (5, 'Tomato'), (2, 'Product 1'), (3, 'Product 2'), (4, 'Tomato'), (5, 'Tomato'), (2, 'Product 1'), (3, 'Product 2'), (4, 'Tomato'), (5, 'Tomato')], help_text='Seasonality type to be used.', null=True)),
                ('will_roll_over', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seasonality',
                'verbose_name_plural': 'Seasonalities',
            },
        ),
        migrations.CreateModel(
            name='SeasonalityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(-1, '---Select Month---'), (0, 'All'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_f_year', to='dates.FinancialYear')),
                ('product', models.ManyToManyField(blank=True, related_name='product_seasonality', to='products.Product')),
            ],
            options={
                'verbose_name': 'Seasonality Value',
                'verbose_name_plural': 'Seasonality Values',
            },
        ),
        migrations.AddField(
            model_name='seasonality',
            name='seasonality_values',
            field=models.ManyToManyField(blank=True, related_name='seasonality_values', to='seasonality.SeasonalityValue'),
        ),
        migrations.AddField(
            model_name='seasonality',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_type', to='dates.FinancialYear'),
        ),
    ]
