# Generated by Django 2.0 on 2019-09-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasonality', '0002_productseasonality_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productseasonality',
            old_name='capacity',
            new_name='demand_percentage',
        ),
    ]
