# Generated by Django 2.0 on 2019-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonality', '0003_auto_20190907_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='productseasonality',
            name='value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
