# Generated by Django 2.0 on 2019-09-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasonality', '0004_productseasonality_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productseasonality',
            old_name='value',
            new_name='demand_value',
        ),
    ]
