# Generated by Django 2.0 on 2019-10-14 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_financialyear'),
        ('seasonality', '0006_auto_20191013_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='productseasonality',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_f_year', to='dates.FinancialYear'),
        ),
    ]
