# Generated by Django 2.0 on 2019-11-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonality', '0007_productseasonality_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productseasonality',
            name='demand_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
