# Generated by Django 2.0 on 2019-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonality', '0009_seasonality_seasonalityvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productseasonality',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='productseasonality',
            name='product',
        ),
        migrations.AddField(
            model_name='seasonality',
            name='will_roll_over',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductSeasonality',
        ),
    ]
