# Generated by Django 2.2.7 on 2019-11-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonality', '0010_auto_20191112_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonalityvalue',
            name='seasonality',
        ),
        migrations.AddField(
            model_name='seasonality',
            name='seasonality_values',
            field=models.ManyToManyField(blank=True, related_name='seasonality_values', to='seasonality.SeasonalityValue'),
        ),
    ]
