# Generated by Django 2.0 on 2020-05-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dates', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('inflation', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('product_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_f_year', to='dates.FinancialYear')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_product', to='products.Product')),
            ],
            options={
                'verbose_name': 'Product Revenue',
                'verbose_name_plural': 'Products Revenue',
            },
        ),
    ]
