# Generated by Django 2.1.4 on 2019-05-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasonality', '0001_initial'),
        ('rampup', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_1_revenue', models.FloatField()),
                ('average_revenue_per_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('month_1_ramp_up', models.ManyToManyField(to='rampup.CapacityRampUp')),
                ('month_1_seasonality', models.ManyToManyField(to='seasonality.ProductSeasonality')),
            ],
        ),
    ]
