# Generated by Django 2.0 on 2019-08-20 04:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seasonality', '0002_auto_20190820_0411'),
        ('products', '0004_product_sale'),
        ('revenues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'verbose_name': 'Product Revenue', 'verbose_name_plural': 'Products Revenue'},
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='average_revenue_per_month',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='month_1_ramp_up',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='month_1_revenue',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='month_1_seasonality',
        ),
        migrations.AddField(
            model_name='revenue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_revenue', to='products.Product'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='product_revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='revenue',
            name='seasonality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonalityrevenue', to='seasonality.ProductSeasonality'),
        ),
    ]
