# Generated by Django 2.0 on 2019-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0002_auto_20190907_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrevenue',
            name='inflation',
            field=models.FloatField(default=0),
        ),
    ]
