# Generated by Django 2.0 on 2019-09-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0003_auto_20190908_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrevenue',
            name='product_rampup',
        ),
    ]
