# Generated by Django 2.0 on 2019-09-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampup', '0003_productrampup_description'),
        ('revenues', '0004_remove_productrevenue_product_rampup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrevenue',
            name='product_rampup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_product_rampup', to='rampup.ProductRampUp'),
        ),
    ]
