# Generated by Django 2.0 on 2019-11-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0005_productrevenue_product_rampup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrevenue',
            name='period',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
