# Generated by Django 2.0 on 2019-11-02 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_financialyear_inflation'),
        ('revenues', '0006_productrevenue_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrevenue',
            old_name='period',
            new_name='month',
        ),
        migrations.AddField(
            model_name='productrevenue',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_f_year', to='dates.FinancialYear'),
        ),
    ]
