# Generated by Django 2.0 on 2019-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0007_auto_20191102_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrevenue',
            name='product_rampup',
        ),
        migrations.RemoveField(
            model_name='productrevenue',
            name='product_seasonality',
        ),
        migrations.AlterField(
            model_name='productrevenue',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
    ]
