# Generated by Django 2.0 on 2019-11-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0008_auto_20191104_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrevenue',
            name='inflation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productrevenue',
            name='product_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
