# Generated by Django 2.0 on 2019-11-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0005_auto_20191109_1333'),
        ('products', '0037_auto_20191112_0405'),
        ('revenues', '0009_auto_20191108_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRevenue',
            new_name='Revenue',
        ),
    ]
