# Generated by Django 2.0 on 2019-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_financialyear_inflation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='description',
            field=models.CharField(default='Year 1', max_length=100),
        ),
    ]
