# Generated by Django 2.0 on 2019-11-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_auto_20191104_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='inflation',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
