# Generated by Django 2.1.4 on 2019-05-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=50)),
                ('average_unit_price', models.FloatField(default=10)),
                ('average_quantity_per_month', models.FloatField(default=1.0)),
                ('average_revenue_per_month', models.FloatField(blank=True)),
            ],
        ),
    ]
