# Generated by Django 2.0 on 2019-09-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='value',
            new_name='total_sale_revenue',
        ),
        migrations.AddField(
            model_name='sale',
            name='seasonality',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='inflation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='ramp_up_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True),
        ),
    ]
