# Generated by Django 2.1.4 on 2019-05-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessplan', '0002_auto_20190519_0843'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='average_revenue_per_month',
        ),
        migrations.AddField(
            model_name='products',
            name='business_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='businessplan.BusinessDetails'),
            preserve_default=False,
        ),
    ]
