# Generated by Django 2.1.4 on 2019-05-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190519_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='business_name',
        ),
        migrations.AddField(
            model_name='products',
            name='average_revenue_per_month',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
