# Generated by Django 2.0 on 2019-09-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190907_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Product Sale', 'verbose_name_plural': 'Product Sales'},
        ),
    ]
