# Generated by Django 2.0 on 2019-09-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190907_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='inflation',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='ramp_up_capacity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seasonality',
        ),
    ]
