# Generated by Django 2.0 on 2019-09-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190908_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='period',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
