# Generated by Django 2.0 on 2019-10-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191009_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax',
            old_name='value',
            new_name='profit_loss_value',
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_percentage',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tax',
            name='total_tax_value',
            field=models.FloatField(default=0.0),
        ),
    ]
