# Generated by Django 2.0 on 2019-11-02 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_financialyear_inflation'),
        ('products', '0012_auto_20191014_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grossprofit',
            name='sale',
        ),
        migrations.AddField(
            model_name='grossprofit',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gross_profit_f_year', to='dates.FinancialYear'),
        ),
        migrations.AddField(
            model_name='grossprofit',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_expenses', to='products.Sale'),
        ),
        migrations.AlterField(
            model_name='grossprofit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_gross_profit', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sale', to='products.Product'),
        ),
    ]
