# Generated by Django 2.0 on 2019-11-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_financialyear_inflation'),
        ('products', '0013_auto_20191102_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='sale',
        ),
        migrations.AddField(
            model_name='expense',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_f_year', to='dates.FinancialYear'),
        ),
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
