# Generated by Django 2.0 on 2019-11-03 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_financialyear_inflation'),
        ('products', '0014_auto_20191103_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitbeforetax',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_before_tax_f_year', to='dates.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='profitbeforetax',
            name='expense',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profitbeforetax',
            name='gross',
            field=models.FloatField(),
        ),
    ]
