# Generated by Django 2.0 on 2019-11-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_financialyear_inflation'),
        ('products', '0017_auto_20191103_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='total',
        ),
        migrations.RemoveField(
            model_name='netprofit',
            name='tax',
        ),
        migrations.AddField(
            model_name='netprofit',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='net_profit_f_year', to='dates.FinancialYear'),
        ),
        migrations.AddField(
            model_name='profitbeforetax',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='profitbeforetax',
            name='monthly_gross_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
