# Generated by Django 2.0 on 2019-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20191103_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='profit_loss_value',
            field=models.FloatField(default=0.0),
        ),
    ]
