# Generated by Django 2.0 on 2019-11-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20191103_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netprofit',
            name='net_profit',
            field=models.FloatField(default=0.0),
        ),
    ]
