# Generated by Django 2.0 on 2019-11-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20191104_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
