# Generated by Django 2.0 on 2019-11-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20191107_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_quantity_per_month',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_revenue_per_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profitbeforetax',
            name='total_gross_value',
            field=models.FloatField(default=0.0),
        ),
    ]
