# Generated by Django 2.0 on 2019-11-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20191107_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_sale_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
