# Generated by Django 2.0 on 2019-11-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_auto_20191104_1904'),
        ('products', '0025_auto_20191109_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_profit_f_year', to='dates.FinancialYear'),
        ),
        migrations.AddField(
            model_name='sale',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='monthly_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
