# Generated by Django 2.0 on 2019-11-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20191109_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='financial_year',
        ),
    ]
