# Generated by Django 2.0 on 2019-11-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20191109_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grossprofit',
            name='cost_of_sale',
            field=models.PositiveSmallIntegerField(default=0, help_text='In percentage'),
        ),
    ]
