# Generated by Django 2.0 on 2019-11-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20191109_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='profit_loss_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tax',
            name='total_tax_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
