# Generated by Django 2.0 on 2019-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20191109_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_quantity_per_month',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
